{
 "title": "DynamoDB Monitoring",
 "tags": [
  "dynamodb",
  "aws"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Read Capacity Units",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Consumed Read Capacity",
     "dimensions": { "TableName": "${name_prefix}-secrets" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Write Capacity Units",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Consumed Write Capacity",
     "dimensions": { "TableName": "${name_prefix}-secrets" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttled Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Read Throttles",
     "dimensions": { "TableName": "${name_prefix}-secrets" },
     "metricName": "ReadThrottledEvents",
     "namespace": "AWS/DynamoDB",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "Write Throttles",
     "dimensions": { "TableName": "${name_prefix}-secrets" },
     "metricName": "WriteThrottledEvents",
     "namespace": "AWS/DynamoDB",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}