{
 "title": "SQS Queues Monitoring",
 "tags": [
  "sqs",
  "aws"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Messages Visible",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "secrets-journal-queue",
     "dimensions": {
      "QueueName": "${name_prefix}-secrets-journal-queue"
     },
     "metricName": "ApproximateNumberOfVisibleMessages",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "alias": "qr-code-queue",
     "dimensions": { "QueueName": "${name_prefix}-qr-code-queue" },
     "metricName": "ApproximateNumberOfVisibleMessages",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "secrets-journal-queue",
     "dimensions": {
      "QueueName": "${name_prefix}-secrets-journal-queue"
     },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "qr-code-queue",
     "dimensions": { "QueueName": "${name_prefix}-qr-code-queue" },
     "metricName": "NumberOfMessagesSent",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "secrets-journal-queue",
     "dimensions": {
      "QueueName": "${name_prefix}-secrets-journal-queue"
     },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "qr-code-queue",
     "dimensions": { "QueueName": "${name_prefix}-qr-code-queue" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}