{
 "title": "AWS Lambda Monitoring",
 "tags": [
  "lambda",
  "aws",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "namespace": "AWS/Lambda",
     "metricName": "Invocations",
     "dimensions": { "FunctionName": "$functionName" },
     "statistic": "Sum",
     "period": "300",
     "region": "$region",
     "accountId": "$accountId"
    }
   ]
  },
  {
   "title": "Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "namespace": "AWS/Lambda",
     "metricName": "Errors",
     "dimensions": { "FunctionName": "$functionName" },
     "statistic": "Sum",
     "period": "300",
     "region": "$region",
     "accountId": "$accountId"
    }
   ]
  },
  {
   "title": "Lambda Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "namespace": "AWS/Lambda",
     "metricName": "Duration",
     "dimensions": {
      "FunctionName": "aws-upc-pfg-infra-dev-secrets_function"
     },
     "statistic": "Average",
     "period": "300",
     "region": "us-east-1",
     "accountId": "389011575948"
    }
   ]
  }
 ]
}