name: AWS UPC PFG - Update Infra

on:
  push:
    branches: ['main']

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Create SSH key for Grafana
        run: |
          mkdir -p keys
          echo "${{ secrets.GRAFANA_SSH_PUBLIC_KEY }}" > keys/grafana_key.pub
          echo "${{ secrets.GRAFANA_SSH_PRIVATE_KEY }}" > keys/grafana_key
          chmod 644 keys/grafana_key.pub
          chmod 600 keys/grafana_key

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform and upload Lambdas
        run: terraform apply -var "account_name=${{secrets.ACCOUNT_NAME}}" -var "sender_email=${{secrets.SENDER_EMAIL}}" --auto-approve
        
